<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-11-28 14:52

$extensionPath = t3lib_extMgm::extPath('cabag_langlink');
return array(
	'tx_cabaglanglink_browselinkshook' => $extensionPath . 'typo3_versions/' . CabagLanglink_TYPO3_version . '/class.tx_cabaglanglink_browseLinksHook.php',
	'tx_cabaglanglink_browslinks' => $extensionPath . 'typo3_versions/' . CabagLanglink_TYPO3_version . '/class.tx_cabaglanglink_browslinks.php',
);
?>